### ISSUE TITLE
Multiple elements

### ISSUE THREAD

**Issue by DENYHAX** [itemsapi/website-to-json#3]
var trim = require('trim')
var wtj = require('website-to-json')

wtj.extractData('http://survivorsrest.com/prices/kotk/', {
  fields: ['data'],
  parse: function($) {
    return {
      item_name: trim($(".item_acc_title").text()),
      price: trim($(".item_acc_overlay span").text())
    }
  }
})
.then(function(res) {
console.log(JSON.stringify(res, null, 2));
})

The result is : 
{
  "data": {
    "item_name": "Hizzy Tux T-ShirtJ!nx  T-ShirtEvil..............",
    "price": "$11,999.99$3,317.20$1,774.50................"
  },
  "url": "http://survivorsrest.com/prices/kotk/",
  "originalUrl": "http://survivorsrest.com/prices/kotk/"
}

But i want it like this : 
{
  "data": {
    "item_name": "Hizzy Tux T-Shirt",
    "price": "$11,999.99"
},
{
  "data": {
    "item_name": "J!nx  T-Shirt",
    "price": "$3,317.20"
},
...

How can i fix this problem?

**Comment by cigolpl** [comment]
Hello,

Let's try this:

```js
var wtj = require('website-to-json');
var trim = require('trim');

wtj.extractData('survivorsrest.com/prices/kotk/', {
  fields: ['data'],
  parse: function($) {
    return $('.item_acc_wrap').map(function(val) {
      return {
        title: $(this).find('.item_acc_title').text(),
        price: $(this).find('.item_acc_overlay span').text()
      }
    }).get()
  }
})
.then(function(res) {
  console.log(JSON.stringify(res, null, 2));
})
```

Btw if you format your code and use "```js" and "```" around your javascript code - it will be more readable.

**Comment by DENYHAX** [comment]
Thanks for your help! 😀😀
